INSERT INTO GITHUB_PROJECT (ORG_NAME, REPO_NAME) VALUES ("A", "B");
INSERT INTO GITHUB_PROJECT (ORG_NAME, REPO_NAME) VALUES ("A1", "B1");
INSERT INTO GITHUB_PROJECT (ORG_NAME, REPO_NAME) VALUES ("A1", "B2");